// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlgpjITqnDhvWPK2IWtimka52q7atjuB8',
    appId: '1:477231987563:web:638412bd19456ce46a6a2e',
    messagingSenderId: '477231987563',
    projectId: 'touchify-mouse',
    authDomain: 'touchify-mouse.firebaseapp.com',
    storageBucket: 'touchify-mouse.firebasestorage.app',
    measurementId: 'G-GZWVMEQ6QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFsUCfZJqL7ZSkayas6kCfAudksPckns',
    appId: '1:477231987563:android:badb5fc122012dd76a6a2e',
    messagingSenderId: '477231987563',
    projectId: 'touchify-mouse',
    storageBucket: 'touchify-mouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrPFoklqXg-tlhoScJnoPI2omyvKN6Oo',
    appId: '1:477231987563:ios:c8bb12abe03d60c86a6a2e',
    messagingSenderId: '477231987563',
    projectId: 'touchify-mouse',
    storageBucket: 'touchify-mouse.firebasestorage.app',
    iosBundleId: 'com.example.touchifyMouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtrPFoklqXg-tlhoScJnoPI2omyvKN6Oo',
    appId: '1:477231987563:ios:c8bb12abe03d60c86a6a2e',
    messagingSenderId: '477231987563',
    projectId: 'touchify-mouse',
    storageBucket: 'touchify-mouse.firebasestorage.app',
    iosBundleId: 'com.example.touchifyMouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlgpjITqnDhvWPK2IWtimka52q7atjuB8',
    appId: '1:477231987563:web:43f83af695adbc3f6a6a2e',
    messagingSenderId: '477231987563',
    projectId: 'touchify-mouse',
    authDomain: 'touchify-mouse.firebaseapp.com',
    storageBucket: 'touchify-mouse.firebasestorage.app',
    measurementId: 'G-WJGSWEJXPR',
  );
}
